### ISSUE TITLE
Multi launch when translate

### ISSUE THREAD

**Issue by OneMiay** [yasirtug/ni-translate#15]
![Screenshot 2020-12-03 00:42:39](https://user-images.githubusercontent.com/1555673/100935375-0529fb00-34be-11eb-8a5d-7a84595464bf.png)

**Comment by yasirtug** [comment]
This is because I didn't implement "already running" functionality.
But you may be facing with this because of session restoring feature of your desktop env. It starts previously opened apps again. Eventually because none of them ever stops, they stack like this with every log in. If this is the case, you can probably exclude ni-translate from that feature in settings.
Also, you can kill them all with `killall ni-translate` command.
